server:
  port: 8080
  servlet:
    context-path: /webapp
spring:
  application:
    name: springlinhtinh
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
    hikari:
      maximum-pool-size: 20 #connection đang làm việc
      minimum-idle: 10 #connection nhàn rỗi, dự bị
      connection-timeout: 30000 #30s
      idle-timeout: 600000 #10p
      max-lifetime: 1800000 #tồn tại 30p khi k làm việc
      pool-name: hikari-connection-pool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 36000

